"""Verify and fix all Render env vars."""
import json
import urllib.error
import urllib.request

KEY = "rnd_9ZDHORtwgArjvCZGNuUYxgNYpldx"
SVC = "srv-da9hg71f2nfc73fj7m90"
H = {"Authorization": f"Bearer {KEY}", "Accept": "application/json", "Content-Type": "application/json"}

NEON = "postgresql+asyncpg://neondb_owner:npg_XS48EVkFOGQr@ep-royal-cell-azlddqmb-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?ssl=require"

REQUIRED = {
    "APP_NAME":                     "DigitalMyHotels",
    "APP_ENV":                      "production",
    "DEBUG":                        "false",
    "ACCESS_TOKEN_EXPIRE_MINUTES":  "15",
    "REFRESH_TOKEN_EXPIRE_DAYS":    "14",
    "REFRESH_COOKIE_SECURE":        "true",
    "REFRESH_COOKIE_SAMESITE":      "none",
    "REFRESH_COOKIE_DOMAIN":        ".onrender.com",
    "STORAGE_BACKEND":              "b2",
    "B2_ENDPOINT":                  "https://s3.us-east-005.backblazeb2.com",
    "B2_BUCKET_NAME":               "Digitialmyhotels",
    "B2_KEY_ID":                    "6adfc5a171f7",
    "B2_APPLICATION_KEY":           "0058fc7fb4f2cdf6165ef831d6b2209566658cb6e3",
    "B2_PUBLIC_BASE_URL":           "",
    "B2_REGION":                    "us-east-005",
    "CORS_ORIGINS":                 '["https://digitalmyhotels.vercel.app"]',
    "EMAIL_BACKEND":                "stub",
    "EMAIL_FROM":                   "noreply@digitalmyhotels.in",
    "RATE_LIMIT_LOGIN_PER_MINUTE":  "10",
    "PYTHON_VERSION":               "3.11.0",
    "DATABASE_URL":                 NEON,
    "UPI_ENCRYPTION_KEY":           "ctLnotPJiqVgA2CvMitzzG8vGQcZZwIanj_EuKKIG7M=",
}


def call(method, path, body=None):
    url = f"https://api.render.com/v1{path}"
    data = json.dumps(body).encode() if body else None
    req = urllib.request.Request(url, data=data, method=method, headers=H)
    try:
        r = urllib.request.urlopen(req)
        raw = r.read()
        return json.loads(raw) if raw else {}, r.status
    except urllib.error.HTTPError as e:
        return {"err": e.read().decode()[:200]}, e.code


# Fetch current env vars
raw, code = call("GET", f"/services/{SVC}/env-vars")
current: dict[str, str] = {}
for item in (raw if isinstance(raw, list) else []):
    ev = item.get("envVar", item)
    if ev.get("key"):
        current[ev["key"]] = ev.get("value", "")

print("=== Render Environment Audit ===\n")
issues: list[str] = []

REDACT = {"UPI_ENCRYPTION_KEY", "B2_APPLICATION_KEY", "DATABASE_URL", "SECRET_KEY"}

for key, expected in sorted(REQUIRED.items()):
    actual = current.get(key)
    redacted = key in REDACT

    if actual is None:
        print(f"  ❌ MISSING       {key}")
        issues.append(key)
    elif actual == expected:
        display = ("*" * 8) if redacted else (actual[:50] if len(actual) <= 50 else actual[:47] + "...")
        print(f"  ✅ OK            {key:<35} = {display}")
    else:
        print(f"  ⚠️  MISMATCH     {key}")
        if not redacted:
            print(f"       expected: {expected[:70]}")
            print(f"       actual:   {actual[:70]}")
        issues.append(key)

# Check SECRET_KEY is set (generated by Render — we can't predict the value)
if current.get("SECRET_KEY"):
    print(f"  ✅ OK            SECRET_KEY                          = {'*'*8} ({len(current['SECRET_KEY'])} chars)")
else:
    print("  ❌ MISSING       SECRET_KEY")
    issues.append("SECRET_KEY")

print(f"\n{'='*55}")
if not issues:
    print("✅ ALL ENVIRONMENT VARIABLES ARE CORRECT")
else:
    print(f"⚠️  {len(issues)} ISSUE(S) FOUND: {', '.join(issues)}")
    print("\nAuto-fixing issues...")

    # Build corrected full env var list
    full_vars = []
    for key, val in REQUIRED.items():
        full_vars.append({"key": key, "value": val})
    # Keep SECRET_KEY as-is if Render generated one
    if current.get("SECRET_KEY"):
        full_vars.append({"key": "SECRET_KEY", "value": current["SECRET_KEY"]})

    result, code = call("PUT", f"/services/{SVC}/env-vars", full_vars)
    print(f"  PUT env-vars: HTTP {code}")
    if code == 200:
        print("  ✅ All environment variables corrected")
    else:
        print(f"  Response: {json.dumps(result)[:300]}")

print(f"\nTotal env vars on Render: {len(current)}")
