"""figma gap batch: bed_type, booking contact/vehicle, hotel_service_items

Revision ID: 0193cb441ff5
Revises: 9332942844b7
Create Date: 2026-08-15 18:58:52.294920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0193cb441ff5'
down_revision: Union[str, None] = '9332942844b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_service_items',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_hotel_service_items_hotel_id_hotels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hotel_service_items')),
    sa.UniqueConstraint('hotel_id', 'name', name='uq_service_item_hotel_name')
    )
    op.create_index(op.f('ix_hotel_service_items_hotel_id'), 'hotel_service_items', ['hotel_id'], unique=False)
    op.add_column('bookings', sa.Column('emergency_contact_name', sa.String(length=200), nullable=True))
    op.add_column('bookings', sa.Column('emergency_contact_relation', sa.String(length=100), nullable=True))
    op.add_column('bookings', sa.Column('emergency_contact_phone', sa.String(length=32), nullable=True))
    op.add_column('bookings', sa.Column('vehicle_number', sa.String(length=32), nullable=True))
    op.add_column('bookings', sa.Column('vehicle_type', sa.String(length=40), nullable=True))
    op.add_column('bookings', sa.Column('parking_slot', sa.String(length=40), nullable=True))
    op.add_column('rooms', sa.Column('bed_type', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'bed_type')
    op.drop_column('bookings', 'parking_slot')
    op.drop_column('bookings', 'vehicle_type')
    op.drop_column('bookings', 'vehicle_number')
    op.drop_column('bookings', 'emergency_contact_phone')
    op.drop_column('bookings', 'emergency_contact_relation')
    op.drop_column('bookings', 'emergency_contact_name')
    op.drop_index(op.f('ix_hotel_service_items_hotel_id'), table_name='hotel_service_items')
    op.drop_table('hotel_service_items')
    # ### end Alembic commands ###
