"""add_registration_next_number_to_hotel_settings

Revision ID: 2ced3e1cf0ee
Revises: 8e0e54208fb5
Create Date: 2026-08-29 19:41:45.094959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2ced3e1cf0ee'
down_revision: Union[str, None] = '8e0e54208fb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('hotel_settings', sa.Column('registration_next_number', sa.Integer(), nullable=True))
    op.execute("UPDATE hotel_settings SET registration_next_number = 1")
    op.alter_column('hotel_settings', 'registration_next_number', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel_settings', 'registration_next_number')
    # ### end Alembic commands ###
