"""foreign guest details form c

Revision ID: 3098be9b9d72
Revises: 8a8183198d71
Create Date: 2026-09-02 01:08:46.577503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3098be9b9d72'
down_revision: Union[str, None] = '8a8183198d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foreign_guest_details',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('passport_number', sa.String(length=32), nullable=False),
    sa.Column('passport_place_of_issue', sa.String(length=120), nullable=True),
    sa.Column('passport_expiry', sa.Date(), nullable=True),
    sa.Column('visa_number', sa.String(length=40), nullable=True),
    sa.Column('visa_type', sa.String(length=40), nullable=True),
    sa.Column('visa_place_of_issue', sa.String(length=120), nullable=True),
    sa.Column('visa_expiry', sa.Date(), nullable=True),
    sa.Column('place_of_birth', sa.String(length=120), nullable=True),
    sa.Column('country_of_birth', sa.String(length=120), nullable=True),
    sa.Column('nationality', sa.String(length=120), nullable=True),
    sa.Column('arrived_in_india_on', sa.Date(), nullable=True),
    sa.Column('arrival_place', sa.String(length=120), nullable=True),
    sa.Column('coming_from_city', sa.String(length=120), nullable=True),
    sa.Column('coming_from_country', sa.String(length=120), nullable=True),
    sa.Column('next_destination', sa.String(length=120), nullable=True),
    sa.Column('next_destination_country', sa.String(length=120), nullable=True),
    sa.Column('purpose_of_visit', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_foreign_guest_details_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_foreign_guest_details_guest_id_guests')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_foreign_guest_details_hotel_id_hotels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_foreign_guest_details')),
    sa.UniqueConstraint('booking_id', 'guest_id', name='uq_foreign_detail_booking_guest')
    )
    op.create_index(op.f('ix_foreign_guest_details_booking_id'), 'foreign_guest_details', ['booking_id'], unique=False)
    op.create_index(op.f('ix_foreign_guest_details_guest_id'), 'foreign_guest_details', ['guest_id'], unique=False)
    op.create_index(op.f('ix_foreign_guest_details_hotel_id'), 'foreign_guest_details', ['hotel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foreign_guest_details_hotel_id'), table_name='foreign_guest_details')
    op.drop_index(op.f('ix_foreign_guest_details_guest_id'), table_name='foreign_guest_details')
    op.drop_index(op.f('ix_foreign_guest_details_booking_id'), table_name='foreign_guest_details')
    op.drop_table('foreign_guest_details')
    # ### end Alembic commands ###
