"""add early_checkin and late_checkout fee_per_hour to hotel settings

Revision ID: 75e76ce1f2bf
Revises: 2bb039a3a637
Create Date: 2026-09-02 03:08:42.408039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '75e76ce1f2bf'
down_revision: Union[str, None] = '2bb039a3a637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add nullable first with a default, then make non-nullable.
    op.add_column('hotel_settings', sa.Column('early_checkin_fee_per_hour', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('hotel_settings', sa.Column('late_checkout_fee_per_hour', sa.Numeric(precision=10, scale=2), nullable=True))
    op.execute("UPDATE hotel_settings SET early_checkin_fee_per_hour = 0.00, late_checkout_fee_per_hour = 0.00")
    op.alter_column('hotel_settings', 'early_checkin_fee_per_hour', nullable=False)
    op.alter_column('hotel_settings', 'late_checkout_fee_per_hour', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel_settings', 'late_checkout_fee_per_hour')
    op.drop_column('hotel_settings', 'early_checkin_fee_per_hour')
    # ### end Alembic commands ###
