"""ledger seq column for deterministic ordering

Revision ID: 788a534e7bb2
Revises: 0193cb441ff5
Create Date: 2026-08-15 19:34:14.084497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '788a534e7bb2'
down_revision: Union[str, None] = '0193cb441ff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest_booking_ledger', sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False))
    op.create_unique_constraint(op.f('uq_guest_booking_ledger_seq'), 'guest_booking_ledger', ['seq'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_guest_booking_ledger_seq'), 'guest_booking_ledger', type_='unique')
    op.drop_column('guest_booking_ledger', 'seq')
    # ### end Alembic commands ###
