"""add hourly_rate to room_types

Revision ID: 83ac59174f62
Revises: 75e76ce1f2bf
Create Date: 2026-09-04 18:50:36.258240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '83ac59174f62'
down_revision: Union[str, None] = '75e76ce1f2bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_types', sa.Column('hourly_rate', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_types', 'hourly_rate')
    # ### end Alembic commands ###
