"""notification category deep_link fields

Revision ID: 8e0e54208fb5
Revises: aae2984155e1
Create Date: 2026-08-25 01:39:12.370878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8e0e54208fb5'
down_revision: Union[str, None] = 'aae2984155e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add category as nullable first, backfill, then add NOT NULL constraint.
    op.add_column('notifications', sa.Column('category', sa.String(length=32), nullable=True))
    op.execute("UPDATE notifications SET category = 'front_desk' WHERE category IS NULL")
    op.alter_column('notifications', 'category', nullable=False)

    op.add_column('notifications', sa.Column('deep_link', sa.String(length=512), nullable=True))
    op.create_index('ix_notif_hotel_read', 'notifications', ['hotel_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_category'), 'notifications', ['category'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_category'), table_name='notifications')
    op.drop_index('ix_notif_hotel_read', table_name='notifications')
    op.drop_column('notifications', 'deep_link')
    op.drop_column('notifications', 'category')
    # ### end Alembic commands ###
