"""initial schema

Revision ID: 9332942844b7
Revises: 
Create Date: 2026-08-15 16:40:54.641226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9332942844b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('logo_object_key', sa.String(length=512), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('postal_code', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hotels'))
    )
    op.create_index(op.f('ix_hotels_slug'), 'hotels', ['slug'], unique=True)
    op.create_index(op.f('ix_hotels_status'), 'hotels', ['status'], unique=False)
    op.create_table('roles',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('subscription_plans',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_plans')),
    sa.UniqueConstraint('code', name=op.f('uq_subscription_plans_code'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('must_reset_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_token_hash', sa.String(length=128), nullable=True),
    sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('hotel_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_audit_logs_hotel_id_hotels'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_hotel_id'), 'audit_logs', ['hotel_id'], unique=False)
    op.create_table('daily_closings',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('checkins_count', sa.Integer(), nullable=False),
    sa.Column('checkouts_count', sa.Integer(), nullable=False),
    sa.Column('current_guests_count', sa.Integer(), nullable=False),
    sa.Column('occupancy_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cash_collected', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('upi_collected', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_expenses', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('refunds_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('dues_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('closed_by_id', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopen_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open','closed')", name=op.f('ck_daily_closings_daily_closing_status')),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], name=op.f('fk_daily_closings_closed_by_id_users')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_daily_closings_hotel_id_hotels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_closings'))
    )
    op.create_index(op.f('ix_daily_closings_business_date'), 'daily_closings', ['business_date'], unique=False)
    op.create_index(op.f('ix_daily_closings_hotel_id'), 'daily_closings', ['hotel_id'], unique=False)
    op.create_table('expense_categories',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_expense_categories_hotel_id_hotels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_categories'))
    )
    op.create_index(op.f('ix_expense_categories_hotel_id'), 'expense_categories', ['hotel_id'], unique=False)
    op.create_table('gst_settings',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('is_gst_registered', sa.Boolean(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('default_cgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('default_sgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('default_igst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_gst_settings_hotel_id_hotels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gst_settings')),
    sa.UniqueConstraint('hotel_id', name=op.f('uq_gst_settings_hotel_id'))
    )
    op.create_table('guests',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('id_proof_type', sa.String(length=64), nullable=True),
    sa.Column('id_last4', sa.String(length=4), nullable=True),
    sa.Column('id_encrypted', sa.Text(), nullable=True),
    sa.Column('id_verification_status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_guests_hotel_id_hotels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guests')),
    sa.UniqueConstraint('hotel_id', 'normalized_phone', name='uq_guest_hotel_phone')
    )
    op.create_index(op.f('ix_guests_hotel_id'), 'guests', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_guests_id_last4'), 'guests', ['id_last4'], unique=False)
    op.create_index(op.f('ix_guests_normalized_phone'), 'guests', ['normalized_phone'], unique=False)
    op.create_table('hotel_memberships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_hotel_memberships_hotel_id_hotels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_hotel_memberships_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_hotel_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hotel_memberships')),
    sa.UniqueConstraint('user_id', 'hotel_id', name='uq_membership_user_hotel')
    )
    op.create_index(op.f('ix_hotel_memberships_hotel_id'), 'hotel_memberships', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_hotel_memberships_user_id'), 'hotel_memberships', ['user_id'], unique=False)
    op.create_table('hotel_payment_config',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('upi_id_encrypted', sa.Text(), nullable=True),
    sa.Column('upi_id_last4', sa.String(length=4), nullable=True),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('logo_object_key', sa.String(length=512), nullable=True),
    sa.Column('qr_object_key', sa.String(length=512), nullable=True),
    sa.Column('qr_version', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_hotel_payment_config_hotel_id_hotels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_hotel_payment_config_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hotel_payment_config')),
    sa.UniqueConstraint('hotel_id', name='uq_payment_config_hotel')
    )
    op.create_table('hotel_settings',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('check_in_time', sa.Time(), nullable=False),
    sa.Column('check_out_time', sa.Time(), nullable=False),
    sa.Column('cancellation_policy', sa.Text(), nullable=True),
    sa.Column('no_show_policy', sa.Text(), nullable=True),
    sa.Column('invoice_prefix', sa.String(length=32), nullable=False),
    sa.Column('invoice_next_number', sa.Integer(), nullable=False),
    sa.Column('booking_prefix', sa.String(length=32), nullable=False),
    sa.Column('booking_next_number', sa.Integer(), nullable=False),
    sa.Column('tax_inclusive_pricing', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('early_checkin_grace_minutes', sa.Integer(), nullable=False),
    sa.Column('late_checkout_grace_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_hotel_settings_hotel_id_hotels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hotel_settings')),
    sa.UniqueConstraint('hotel_id', name=op.f('uq_hotel_settings_hotel_id'))
    )
    op.create_table('notifications',
    sa.Column('hotel_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_notifications_hotel_id_hotels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_hotel_id'), 'notifications', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], name=op.f('fk_refresh_tokens_replaced_by_id_refresh_tokens')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('room_types',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('extra_guest_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_occupancy', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_room_types_hotel_id_hotels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_types')),
    sa.UniqueConstraint('hotel_id', 'code', name='uq_room_type_hotel_code')
    )
    op.create_index(op.f('ix_room_types_hotel_id'), 'room_types', ['hotel_id'], unique=False)
    op.create_table('shift_handovers',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('from_user_id', sa.UUID(), nullable=False),
    sa.Column('to_user_id', sa.UUID(), nullable=True),
    sa.Column('opening_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('closing_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payments_collected', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pending_payments', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('room_issues', sa.Text(), nullable=True),
    sa.Column('pending_issues', sa.Text(), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('fk_shift_handovers_from_user_id_users')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_shift_handovers_hotel_id_hotels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name=op.f('fk_shift_handovers_to_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_handovers'))
    )
    op.create_index(op.f('ix_shift_handovers_hotel_id'), 'shift_handovers', ['hotel_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('grace_days', sa.Integer(), nullable=False),
    sa.Column('payment_status', sa.String(length=32), nullable=False),
    sa.Column('allow_view_after_expiry', sa.Boolean(), nullable=False),
    sa.Column('block_transactions_after_expiry', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('trial','active','expiring_soon','expired','suspended')", name=op.f('ck_subscriptions_subscription_status')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_subscriptions_hotel_id_hotels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], name=op.f('fk_subscriptions_plan_id_subscription_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index(op.f('ix_subscriptions_hotel_id'), 'subscriptions', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_table('vendors',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('upi_id_encrypted', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_vendors_hotel_id_hotels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors'))
    )
    op.create_index(op.f('ix_vendors_hotel_id'), 'vendors', ['hotel_id'], unique=False)
    op.create_table('bookings',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('booking_number', sa.String(length=64), nullable=False),
    sa.Column('primary_guest_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payment_status', sa.String(length=32), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.Column('room_count', sa.Integer(), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('advance_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('security_deposit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_status IN ('unpaid','partial','paid','refunded','cancelled')", name=op.f('ck_bookings_booking_payment_status')),
    sa.CheckConstraint("status IN ('pending','confirmed','checked_in','checked_out','cancelled','no_show')", name=op.f('ck_bookings_booking_status')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_bookings_created_by_id_users')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_bookings_hotel_id_hotels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_guest_id'], ['guests.id'], name=op.f('fk_bookings_primary_guest_id_guests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings')),
    sa.UniqueConstraint('hotel_id', 'booking_number', name='uq_booking_number')
    )
    op.create_index(op.f('ix_bookings_hotel_id'), 'bookings', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('expenses',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=16), nullable=False),
    sa.Column('payment_status', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bill_number', sa.String(length=64), nullable=True),
    sa.Column('bill_date', sa.Date(), nullable=True),
    sa.Column('attachment_object_key', sa.String(length=512), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_method IN ('cash','upi')", name=op.f('ck_expenses_expense_payment_method')),
    sa.CheckConstraint("status IN ('draft','submitted','approved','paid','rejected')", name=op.f('ck_expenses_expense_status')),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_expenses_approved_by_id_users')),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], name=op.f('fk_expenses_category_id_expense_categories')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_expenses_created_by_id_users')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_expenses_hotel_id_hotels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_expenses_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index(op.f('ix_expenses_hotel_id'), 'expenses', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_expenses_status'), 'expenses', ['status'], unique=False)
    op.create_table('guest_documents',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_guest_documents_guest_id_guests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_guest_documents_hotel_id_hotels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guest_documents'))
    )
    op.create_index(op.f('ix_guest_documents_guest_id'), 'guest_documents', ['guest_id'], unique=False)
    op.create_index(op.f('ix_guest_documents_hotel_id'), 'guest_documents', ['hotel_id'], unique=False)
    op.create_table('recurring_expenses',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('frequency', sa.String(length=32), nullable=False),
    sa.Column('custom_interval_days', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('next_run_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reminder_days_before', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("frequency IN ('monthly','quarterly','yearly','custom')", name=op.f('ck_recurring_expenses_recurring_frequency')),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], name=op.f('fk_recurring_expenses_category_id_expense_categories')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_recurring_expenses_hotel_id_hotels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_recurring_expenses_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurring_expenses'))
    )
    op.create_index(op.f('ix_recurring_expenses_hotel_id'), 'recurring_expenses', ['hotel_id'], unique=False)
    op.create_table('rooms',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('room_type_id', sa.UUID(), nullable=False),
    sa.Column('room_number', sa.String(length=32), nullable=False),
    sa.Column('floor', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('available','reserved','occupied','cleaning_required','cleaning_in_progress','clean_ready','inspection_required','maintenance','out_of_service')", name=op.f('ck_rooms_room_status')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_rooms_hotel_id_hotels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], name=op.f('fk_rooms_room_type_id_room_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms')),
    sa.UniqueConstraint('hotel_id', 'room_number', name='uq_room_hotel_number')
    )
    op.create_index(op.f('ix_rooms_hotel_id'), 'rooms', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_rooms_room_type_id'), 'rooms', ['room_type_id'], unique=False)
    op.create_index(op.f('ix_rooms_status'), 'rooms', ['status'], unique=False)
    op.create_table('booking_rooms',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('room_type_id', sa.UUID(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_booking_rooms_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_booking_rooms_hotel_id_hotels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_booking_rooms_room_id_rooms')),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], name=op.f('fk_booking_rooms_room_type_id_room_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_rooms')),
    sa.UniqueConstraint('booking_id', 'room_id', name='uq_booking_room')
    )
    op.create_index(op.f('ix_booking_rooms_booking_id'), 'booking_rooms', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_rooms_hotel_id'), 'booking_rooms', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_booking_rooms_room_id'), 'booking_rooms', ['room_id'], unique=False)
    op.create_table('checkins',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_checkout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_early', sa.Boolean(), nullable=False),
    sa.Column('early_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('performed_by_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_checkins_booking_id_bookings')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_checkins_hotel_id_hotels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], name=op.f('fk_checkins_performed_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkins')),
    sa.UniqueConstraint('booking_id', name=op.f('uq_checkins_booking_id'))
    )
    op.create_index(op.f('ix_checkins_hotel_id'), 'checkins', ['hotel_id'], unique=False)
    op.create_table('checkouts',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('is_early', sa.Boolean(), nullable=False),
    sa.Column('late_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('final_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_due_authorized', sa.Boolean(), nullable=False),
    sa.Column('payment_due_reason', sa.Text(), nullable=True),
    sa.Column('authorized_by_id', sa.UUID(), nullable=True),
    sa.Column('performed_by_id', sa.UUID(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reverse_reason', sa.Text(), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by_id'], ['users.id'], name=op.f('fk_checkouts_authorized_by_id_users')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_checkouts_booking_id_bookings')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_checkouts_hotel_id_hotels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], name=op.f('fk_checkouts_performed_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkouts'))
    )
    op.create_index(op.f('ix_checkouts_booking_id'), 'checkouts', ['booking_id'], unique=False)
    op.create_index(op.f('ix_checkouts_hotel_id'), 'checkouts', ['hotel_id'], unique=False)
    op.create_table('guest_booking_ledger',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('reference_type', sa.String(length=64), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entry_type IN ('debit','credit')", name=op.f('ck_guest_booking_ledger_ledger_entry_type')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_guest_booking_ledger_booking_id_bookings')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_guest_booking_ledger_created_by_id_users')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_guest_booking_ledger_hotel_id_hotels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guest_booking_ledger'))
    )
    op.create_index(op.f('ix_guest_booking_ledger_booking_id'), 'guest_booking_ledger', ['booking_id'], unique=False)
    op.create_index(op.f('ix_guest_booking_ledger_hotel_id'), 'guest_booking_ledger', ['hotel_id'], unique=False)
    op.create_table('guest_registrations',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('registration_number', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('purpose_of_visit', sa.String(length=200), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_guest_registrations_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_guest_registrations_guest_id_guests')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_guest_registrations_hotel_id_hotels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guest_registrations'))
    )
    op.create_index(op.f('ix_guest_registrations_booking_id'), 'guest_registrations', ['booking_id'], unique=False)
    op.create_index(op.f('ix_guest_registrations_guest_id'), 'guest_registrations', ['guest_id'], unique=False)
    op.create_index(op.f('ix_guest_registrations_hotel_id'), 'guest_registrations', ['hotel_id'], unique=False)
    op.create_table('hotel_charges',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('food','laundry','room_service','extra_bed','minibar','transport','other')", name=op.f('ck_hotel_charges_charge_category')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_hotel_charges_booking_id_bookings')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_hotel_charges_created_by_id_users')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_hotel_charges_hotel_id_hotels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_hotel_charges_room_id_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hotel_charges'))
    )
    op.create_index(op.f('ix_hotel_charges_booking_id'), 'hotel_charges', ['booking_id'], unique=False)
    op.create_index(op.f('ix_hotel_charges_hotel_id'), 'hotel_charges', ['hotel_id'], unique=False)
    op.create_table('housekeeping_tasks',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('cleaning_required','cleaning_in_progress','clean_ready','inspection_required','completed','cancelled')", name=op.f('ck_housekeeping_tasks_hk_status')),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_housekeeping_tasks_assigned_to_id_users')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_housekeeping_tasks_booking_id_bookings')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_housekeeping_tasks_hotel_id_hotels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_housekeeping_tasks_room_id_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_housekeeping_tasks'))
    )
    op.create_index(op.f('ix_housekeeping_tasks_hotel_id'), 'housekeeping_tasks', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_housekeeping_tasks_room_id'), 'housekeeping_tasks', ['room_id'], unique=False)
    op.create_index(op.f('ix_housekeeping_tasks_status'), 'housekeeping_tasks', ['status'], unique=False)
    op.create_table('invoices',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('guest_name', sa.String(length=200), nullable=False),
    sa.Column('guest_address', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pdf_object_key', sa.String(length=512), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','generated','partially_paid','paid','cancelled','refunded')", name=op.f('ck_invoices_invoice_status')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_invoices_booking_id_bookings')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_invoices_created_by_id_users')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_invoices_hotel_id_hotels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('hotel_id', 'invoice_number', name='uq_invoice_number')
    )
    op.create_index(op.f('ix_invoices_booking_id'), 'invoices', ['booking_id'], unique=False)
    op.create_index(op.f('ix_invoices_hotel_id'), 'invoices', ['hotel_id'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expected_completion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open','in_progress','resolved','cancelled')", name=op.f('ck_maintenance_records_maintenance_status')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_maintenance_records_created_by_id_users')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_maintenance_records_hotel_id_hotels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_maintenance_records_room_id_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_records'))
    )
    op.create_index(op.f('ix_maintenance_records_hotel_id'), 'maintenance_records', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_room_id'), 'maintenance_records', ['room_id'], unique=False)
    op.create_table('room_amenities',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_room_amenities_hotel_id_hotels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_amenities_room_id_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_amenities')),
    sa.UniqueConstraint('room_id', 'name', name='uq_room_amenity_name')
    )
    op.create_index(op.f('ix_room_amenities_hotel_id'), 'room_amenities', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_room_amenities_room_id'), 'room_amenities', ['room_id'], unique=False)
    op.create_table('room_transfers',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('from_room_id', sa.UUID(), nullable=False),
    sa.Column('to_room_id', sa.UUID(), nullable=False),
    sa.Column('transferred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('performed_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_room_transfers_booking_id_bookings')),
    sa.ForeignKeyConstraint(['from_room_id'], ['rooms.id'], name=op.f('fk_room_transfers_from_room_id_rooms')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_room_transfers_hotel_id_hotels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], name=op.f('fk_room_transfers_performed_by_id_users')),
    sa.ForeignKeyConstraint(['to_room_id'], ['rooms.id'], name=op.f('fk_room_transfers_to_room_id_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_transfers'))
    )
    op.create_index(op.f('ix_room_transfers_booking_id'), 'room_transfers', ['booking_id'], unique=False)
    op.create_index(op.f('ix_room_transfers_hotel_id'), 'room_transfers', ['hotel_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_invoice_items_hotel_id_hotels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_items_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_items'))
    )
    op.create_index(op.f('ix_invoice_items_hotel_id'), 'invoice_items', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_table('payments',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_by_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('corrects_payment_id', sa.UUID(), nullable=True),
    sa.Column('correction_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('cash','upi')", name=op.f('ck_payments_payment_method')),
    sa.CheckConstraint("purpose IN ('advance','stay','deposit','charge','other')", name=op.f('ck_payments_payment_purpose')),
    sa.CheckConstraint("status IN ('pending','completed','failed','refunded','cancelled','corrected')", name=op.f('ck_payments_payment_status')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_payments_booking_id_bookings')),
    sa.ForeignKeyConstraint(['collected_by_id'], ['users.id'], name=op.f('fk_payments_collected_by_id_users')),
    sa.ForeignKeyConstraint(['corrects_payment_id'], ['payments.id'], name=op.f('fk_payments_corrects_payment_id_payments')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_payments_hotel_id_hotels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payments_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_hotel_id'), 'payments', ['hotel_id'], unique=False)
    op.create_table('refunds',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('performed_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('cash','upi')", name=op.f('ck_refunds_refund_method')),
    sa.CheckConstraint("status IN ('pending','completed','cancelled')", name=op.f('ck_refunds_refund_status')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_refunds_booking_id_bookings')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_refunds_hotel_id_hotels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_refunds_payment_id_payments')),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], name=op.f('fk_refunds_performed_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds'))
    )
    op.create_index(op.f('ix_refunds_booking_id'), 'refunds', ['booking_id'], unique=False)
    op.create_index(op.f('ix_refunds_hotel_id'), 'refunds', ['hotel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_hotel_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_booking_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_payments_hotel_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_hotel_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_room_transfers_hotel_id'), table_name='room_transfers')
    op.drop_index(op.f('ix_room_transfers_booking_id'), table_name='room_transfers')
    op.drop_table('room_transfers')
    op.drop_index(op.f('ix_room_amenities_room_id'), table_name='room_amenities')
    op.drop_index(op.f('ix_room_amenities_hotel_id'), table_name='room_amenities')
    op.drop_table('room_amenities')
    op.drop_index(op.f('ix_maintenance_records_room_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_hotel_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_invoices_hotel_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_booking_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_housekeeping_tasks_status'), table_name='housekeeping_tasks')
    op.drop_index(op.f('ix_housekeeping_tasks_room_id'), table_name='housekeeping_tasks')
    op.drop_index(op.f('ix_housekeeping_tasks_hotel_id'), table_name='housekeeping_tasks')
    op.drop_table('housekeeping_tasks')
    op.drop_index(op.f('ix_hotel_charges_hotel_id'), table_name='hotel_charges')
    op.drop_index(op.f('ix_hotel_charges_booking_id'), table_name='hotel_charges')
    op.drop_table('hotel_charges')
    op.drop_index(op.f('ix_guest_registrations_hotel_id'), table_name='guest_registrations')
    op.drop_index(op.f('ix_guest_registrations_guest_id'), table_name='guest_registrations')
    op.drop_index(op.f('ix_guest_registrations_booking_id'), table_name='guest_registrations')
    op.drop_table('guest_registrations')
    op.drop_index(op.f('ix_guest_booking_ledger_hotel_id'), table_name='guest_booking_ledger')
    op.drop_index(op.f('ix_guest_booking_ledger_booking_id'), table_name='guest_booking_ledger')
    op.drop_table('guest_booking_ledger')
    op.drop_index(op.f('ix_checkouts_hotel_id'), table_name='checkouts')
    op.drop_index(op.f('ix_checkouts_booking_id'), table_name='checkouts')
    op.drop_table('checkouts')
    op.drop_index(op.f('ix_checkins_hotel_id'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_booking_rooms_room_id'), table_name='booking_rooms')
    op.drop_index(op.f('ix_booking_rooms_hotel_id'), table_name='booking_rooms')
    op.drop_index(op.f('ix_booking_rooms_booking_id'), table_name='booking_rooms')
    op.drop_table('booking_rooms')
    op.drop_index(op.f('ix_rooms_status'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_room_type_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_hotel_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_recurring_expenses_hotel_id'), table_name='recurring_expenses')
    op.drop_table('recurring_expenses')
    op.drop_index(op.f('ix_guest_documents_hotel_id'), table_name='guest_documents')
    op.drop_index(op.f('ix_guest_documents_guest_id'), table_name='guest_documents')
    op.drop_table('guest_documents')
    op.drop_index(op.f('ix_expenses_status'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_hotel_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_hotel_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_vendors_hotel_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_hotel_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_shift_handovers_hotel_id'), table_name='shift_handovers')
    op.drop_table('shift_handovers')
    op.drop_index(op.f('ix_room_types_hotel_id'), table_name='room_types')
    op.drop_table('room_types')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_hotel_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('hotel_settings')
    op.drop_table('hotel_payment_config')
    op.drop_index(op.f('ix_hotel_memberships_user_id'), table_name='hotel_memberships')
    op.drop_index(op.f('ix_hotel_memberships_hotel_id'), table_name='hotel_memberships')
    op.drop_table('hotel_memberships')
    op.drop_index(op.f('ix_guests_normalized_phone'), table_name='guests')
    op.drop_index(op.f('ix_guests_id_last4'), table_name='guests')
    op.drop_index(op.f('ix_guests_hotel_id'), table_name='guests')
    op.drop_table('guests')
    op.drop_table('gst_settings')
    op.drop_index(op.f('ix_expense_categories_hotel_id'), table_name='expense_categories')
    op.drop_table('expense_categories')
    op.drop_index(op.f('ix_daily_closings_hotel_id'), table_name='daily_closings')
    op.drop_index(op.f('ix_daily_closings_business_date'), table_name='daily_closings')
    op.drop_table('daily_closings')
    op.drop_index(op.f('ix_audit_logs_hotel_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_hotels_status'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_slug'), table_name='hotels')
    op.drop_table('hotels')
    # ### end Alembic commands ###
