"""add overdue_notified_at to bookings

Revision ID: 95c1dcc60bfe
Revises: 83ac59174f62
Create Date: 2026-09-04 21:01:02.475605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '95c1dcc60bfe'
down_revision: Union[str, None] = '83ac59174f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('overdue_notified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'overdue_notified_at')
    # ### end Alembic commands ###
