"""add_access_mode_to_hotel_settings

Revision ID: a6254667b789
Revises: 765a2cd99df7
Create Date: 2026-08-29 21:08:05.981667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a6254667b789'
down_revision: Union[str, None] = '765a2cd99df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('hotel_settings', sa.Column('access_mode', sa.String(length=32), nullable=True))
    op.execute("UPDATE hotel_settings SET access_mode = 'full'")
    op.alter_column('hotel_settings', 'access_mode', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel_settings', 'access_mode')
    # ### end Alembic commands ###
