"""expand payment methods to include card, bank_transfer, other

Revision ID: aae2984155e1
Revises: cee32cabc6e3
Create Date: 2026-08-24 23:57:19.584115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aae2984155e1'
down_revision: Union[str, None] = 'cee32cabc6e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
