"""composite indexes for real query paths

Revision ID: cee32cabc6e3
Revises: 788a534e7bb2
Create Date: 2026-08-15 20:05:04.398101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cee32cabc6e3'
down_revision: Union[str, None] = '788a534e7bb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audit_hotel_created', 'audit_logs', ['hotel_id', 'created_at'], unique=False)
    op.create_index('ix_bookings_hotel_checkin', 'bookings', ['hotel_id', 'check_in_date'], unique=False)
    op.create_index('ix_bookings_hotel_status', 'bookings', ['hotel_id', 'status'], unique=False)
    op.create_index('ix_expenses_hotel_date', 'expenses', ['hotel_id', 'expense_date'], unique=False)
    op.create_index('ix_invoices_hotel_date', 'invoices', ['hotel_id', 'invoice_date'], unique=False)
    op.create_index('ix_payments_hotel_paid_at', 'payments', ['hotel_id', 'paid_at'], unique=False)
    op.create_index('ix_rooms_hotel_status', 'rooms', ['hotel_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rooms_hotel_status', table_name='rooms')
    op.drop_index('ix_payments_hotel_paid_at', table_name='payments')
    op.drop_index('ix_invoices_hotel_date', table_name='invoices')
    op.drop_index('ix_expenses_hotel_date', table_name='expenses')
    op.drop_index('ix_bookings_hotel_status', table_name='bookings')
    op.drop_index('ix_bookings_hotel_checkin', table_name='bookings')
    op.drop_index('ix_audit_hotel_created', table_name='audit_logs')
    # ### end Alembic commands ###
